version: '3.8'

services:
  # qms-nextjs:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: qms-nextjs
  #   environment:
  #     - NODE_ENV=production
  #   volumes:
  #     - ./:/usr/src/app
  #   ports:
  #     - "3000:3000"

  nginx:
    image: nginx:1.21.6-alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./landing-page:/var/www/quickq.ma
    ports:
      - "80:80"
      - "443:443"
    # depends_on:
    #   - qms-nextjs
